services:

  web-monitor:

    build: 
      context: .
      network: host

    container_name: proyecto-linux-grupo9

    ports:

      - "8080:80"

    volumes:

      - ./scripts:/var/www/scripts

      - ./web:/var/www/html

      - ./datos:/var/www/datos

      - ./capturas:/var/www/capturas

    restart: unless-stopped

